FROM node:21.4.0-bookworm

RUN apt-get -y update && apt-get -y install graphicsmagick

WORKDIR /app

ENV NODE_ENV=development
ENV PRISMA_OUTPUT="/app/node_modules/.prisma/client"

ENTRYPOINT ["bash", "/app/dev.sh"]
